#numpy


In [1]:
import numpy as np
print (np.__version__)
# tensorflow에 묶여있음

1.22.4


###생성

In [ ]:
# ndarray 만드는 방법

In [9]:
a= np.array([1,2,3,4])
# print 는 내용물만 표시
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
b= np.array([[1,2,3],[4,5,6]])

print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [11]:
c= np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])

print(c)
print(type(c))
# 괄호갯수는 차원의 수로 보면 됨
# array 붙으면 numpy array라고 느끼기

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]
<class 'numpy.ndarray'>


In [12]:
a.shape, b.shape, c.shape
# 파이썬 튜플은 ()형식으로 출력 결과 보셈 괄호로 묶여있음
#  일차원은 4, 형태 원소가 4개있다 ,가 있는 이유는 튜플 표시하기위해 없으면 그냥 integer
# 이차원은 3개짜리가 2개 모여있는 데이터
# (3,2,4)는 4개짜리가 2개 있고 그게 3개 들어있는 데이터

((4,), (2, 3), (3, 2, 4))

In [13]:
c.dtype
# 정수 표시하기 위해 64비트 사용한다는 뜻
# numpy는 하나의 타입만 가능 int면 int, 문자가 섞여있으면 안됨 -->U21 unicode라는 뜻, float

dtype('int64')

In [ ]:
# numpy axis = row의 수 (이차원), axis0->높이 axis1->행 axis2->열 (3차원) 축 기억하기

In [16]:
np.zeros((3,4,2))
# shape떠올리기, 괄호 뒤에서 부터 해석하기

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
a= np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros_like(a)
# 딥러닝 연산 시 똑같은 형태를 만들어야할 때 사용함.

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.arange(10)
# list(range(5)) 는 리스트

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# numpy의 랜덤함수
# 정규분포에서 뽑겠다.
np.random.normal(10,3,(2,3))

array([[13.25174481,  5.18816739, 14.38259653],
       [ 6.41065102, 10.31810595, 14.89147446]])

In [23]:
# 유니폼분포: 0하고 1 사이에서 뽑기
np.random.rand(3,2)

array([[0.05399753, 0.43686393],
       [0.72258167, 0.98247201],
       [0.67138128, 0.95065746]])

In [24]:
# 표준 정규분포
np.random.randn(3,4)


array([[ 0.77239993, -0.33722914,  0.52718072, -1.20914201],
       [-0.02790174, -1.03698098, -1.23690962, -0.36954949],
       [-0.36970902,  0.42687749,  0.15274182, -1.13683563]])

In [27]:
a= np.arange(12)
a
# a를 찍어서 보는 습관 들이기 a.shape()이런거

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a.shape

(12,)

In [31]:
# 형태바꾸기, 이미지에서 많이 씀,
a= a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
a.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [37]:
#  몇개인지는 모르지만 2,2짜리 n개를 원한다. 너가 알아서 채워줘! 할 때 -1사용한다.
a= a.reshape(-1,2,2)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [38]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [39]:
b=np.array([[2,3],[3,4]])
b

array([[2, 3],
       [3, 4]])

In [40]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[2, 3],
        [3, 4]]))

In [41]:
# 산술연산-->같은 자리끼리 계산
a+b, a-b, a*b,a/b

(array([[3, 5],
        [6, 8]]),
 array([[-1, -1],
        [ 0,  0]]),
 array([[ 2,  6],
        [ 9, 16]]),
 array([[0.5       , 0.66666667],
        [1.        , 1.        ]]))

In [43]:
# 매트릭스 연산, 내적
a@b
np.dot(a,b)

array([[ 8, 11],
       [18, 25]])

In [46]:
# 비교연산-->T,F 로 나온다!
a==b
a>b

array([[False, False],
       [False, False]])

In [47]:
a+3
# broadcasting

array([[4, 5],
       [6, 7]])

In [48]:
a+[3]
# 일차원은 모양 맞추기 가능(브로드캐스팅)

array([[4, 5],
       [6, 7]])

In [49]:
a+[2,1]
# 양쪽을 어떻게 바꿔도 안맞으면 에러

array([[3, 3],
       [5, 5]])

In [54]:
a= np.arange(0,12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
np.sum(a)

66

In [56]:
np.sum(a,axis=0)
# ()의 첫번째 칸 = 0번째 축
# 0번째 축으로 더하라

array([12, 15, 18, 21])

In [57]:
np.sum(a,axis=1)
# mean도 마찬가지

array([ 6, 22, 38])

In [58]:
a.sum(axis=0)
# 이렇게도 쓸 수 있당

array([12, 15, 18, 21])

In [ ]:
# 인덱싱: 지정하는 숫자 뽑기. 한개
# 슬라이싱: 어디부터 어디 뽑고싶다. 여러개 -->범위 지정

In [60]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
a[1:5]

array([1, 2, 3, 4])

In [62]:
a[:-1]
# -1은 제일 뒤를 뜻한다. -2는 뒤에서 두번째

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
a[-3:]

array([7, 8, 9])

In [64]:
a=np.arange(1,25).reshape(-1,6)
a
# 5개짜리가 몇개있어야 24개야?

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [66]:
a[1:3]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [68]:
a[0:3,1:3]
# slicing

array([[ 2,  3],
       [ 8,  9],
       [14, 15]])

In [70]:
# fancy indexing
a[[0,2],[0,1]]

array([ 1, 14])

In [72]:
a= np.arange(1,5)
a

array([1, 2, 3, 4])

In [74]:
a[[0,3]]
a[[True,False,True,False]]
# boolean indexing-->t,f 로 지정해서 뽑는 것

array([1, 3])

In [75]:
a= np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
a[a%2 ==0]
# 짝수 뽑고싶어

array([0, 2, 4, 6, 8])

In [80]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
a.reshape(-1)
# a.ravel() --> 일자로 펴라

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [86]:
a= a.reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [93]:
a.reshape(-1,1)


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [98]:
a=a.reshape(-1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
a.shape

(12,)

In [100]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [102]:
b= np.zeros_like(a)
b

array([[0, 0],
       [0, 0]])

In [ ]:
# 단순히 성능으로 판단하기 보다는 이거를 앱으로 배포해본다던지 정확성을 판단할 수 있는 중요도를 판단할 수 있는 시각을 갖는 것도 중요!

In [104]:
# 결합하기
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [0, 0],
       [0, 0]])

In [105]:
np.concatenate((a,b),axis=1)

array([[1, 2, 0, 0],
       [3, 4, 0, 0]])