#svm 이진분류
- diabetes dataset

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

###1. 데이터 준비

In [ ]:
df=pd.read_csv('diabetes.csv')

In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
df.describe().T

count        mean         std     min       25%  \
Pregnancies               768.0    3.845052    3.369578   0.000   1.00000   
Glucose                   768.0  120.894531   31.972618   0.000  99.00000   
BloodPressure             768.0   69.105469   19.355807   0.000  62.00000   
SkinThickness             768.0   20.536458   15.952218   0.000   0.00000   
Insulin                   768.0   79.799479  115.244002   0.000   0.00000   
BMI                       768.0   31.992578    7.884160   0.000  27.30000   
DiabetesPedigreeFunction  768.0    0.471876    0.331329   0.078   0.24375   
Age                       768.0   33.240885   11.760232  21.000  24.00000   
Outcome                   768.0    0.348958    0.476951   0.000   0.00000   

                               50%        75%     max  
Pregnancies                 3.0000    6.00000   17.00  
Glucose                   117.0000  140.25000  199.00  
BloodPressure              72.0000   80.00000  122.00  
SkinThickness              23.0000   32.00000   99.00  
Insulin                    30.5000  127.25000  846.00  
BMI                        32.0000   36.60000   67.10  
DiabetesPedigreeFunction    0.3725    0.62625    2.42  
Age                        29.0000   41.00000   81.00  
Outcome                     0.0000    1.00000    1.00

In [ ]:
df.isna().sum(axis=0)

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

#####이상치

In [ ]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [ ]:
cols=['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

In [ ]:
df[cols]=  df[cols].replace(0, np.nan)

In [ ]:
df.isna().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [ ]:
df.dropna().shape

(392, 9)

In [ ]:
for col in cols:
  df[col]= df[col].fillna(df[col].mean())


In [ ]:
df.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin        BMI  \
0            6    148.0      72.000000       35.00000  155.548223  33.600000   
1            1     85.0      66.000000       29.00000  155.548223  26.600000   
2            8    183.0      64.000000       29.15342  155.548223  23.300000   
3            1     89.0      66.000000       23.00000   94.000000  28.100000   
4            0    137.0      40.000000       35.00000  168.000000  43.100000   
5            5    116.0      74.000000       29.15342  155.548223  25.600000   
6            3     78.0      50.000000       32.00000   88.000000  31.000000   
7           10    115.0      72.405184       29.15342  155.548223  35.300000   
8            2    197.0      70.000000       45.00000  543.000000  30.500000   
9            8    125.0      96.000000       29.15342  155.548223  32.457464   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

###2. 데이터 분리
- test



In [ ]:
x= df.drop('Outcome',axis=1)

y= df['Outcome']


In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2, random_state= 32190403)

In [ ]:
x_train.head()

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin  \
426            0     94.0      72.405184       29.15342  155.548223   
68             1     95.0      66.000000       13.00000   38.000000   
201            1    138.0      82.000000       29.15342  155.548223   
489            8    194.0      80.000000       29.15342  155.548223   
420            1    119.0      88.000000       41.00000  170.000000   

           BMI  DiabetesPedigreeFunction  Age  
426  32.457464                     0.256   25  
68   19.600000                     0.334   25  
201  40.100000                     0.236   28  
489  26.100000                     0.551   67  
420  45.300000                     0.507   26

In [ ]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(x_train)

StandardScaler()

In [ ]:
x_train_s= ss.transform(x_train)
x_train_s

array([[-1.12448323, -0.89437426,  0.00995745, ..., -0.01819492,
        -0.6528554 , -0.69297951],
       [-0.82930038, -0.86182794, -0.52643741, ..., -1.89009735,
        -0.42447571, -0.69297951],
       [-0.82930038,  0.53766374,  0.81346438, ...,  1.09447261,
        -0.7114143 , -0.44425226],
       ...,
       [-0.23893466, -1.25238376, -1.1963883 , ...,  0.2500577 ,
        -0.41861982, -0.69297951],
       [-0.23893466, -0.17835526,  0.00995745, ..., -1.32230111,
        -0.8548836 , -0.85879767],
       [-1.12448323, -0.11326262, -0.69392513, ..., -0.01819492,
         3.66586326, -1.02461584]])

In [ ]:
x_test_s = ss.transform(x_test)
x_test_s

array([[-1.12448323,  0.30983952,  1.31592755, ..., -0.14303201,
         0.77305374, -0.11261592],
       [ 1.53216249, -0.99201321, -0.35894969, ..., -1.22038897,
        -0.81682032,  2.04302025],
       [-0.82930038,  0.70039533,  0.14351348, ..., -0.92921141,
        -0.6528554 , -1.02461584],
       ...,
       [ 0.64661392, -0.4387258 , -2.36880237, ..., -1.24950672,
         0.97800988,  0.13611133],
       [-1.12448323,  0.14710792,  1.14843982, ..., -0.75450487,
         0.10548231, -1.02461584],
       [ 0.64661392, -0.53636476, -0.19146196, ..., -0.25950303,
        -1.04520002,  0.3019295 ]])

In [ ]:
y_train

426    0
68     0
201    0
489    0
420    0
      ..
384    0
241    0
108    0
347    0
371    0
Name: Outcome, Length: 614, dtype: int64

In [ ]:
y_train= y_train.values
y_test= y_test.values

###베이스라인 학습


In [ ]:
from sklearn.svm import SVC
clf = SVC(kernel='linear')
clf.fit(x_train_s, y_train)

SVC(kernel='linear')

In [ ]:
y_pred = clf.predict(x_test_s)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix

cfm = confusion_matrix(y_test, y_pred)
cfm

array([[90, 11],
       [22, 31]])

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

def print_metrics(y_test, y_pred):
  acc= accuracy_score(y_test, y_pred)
  re= recall_score(y_test, y_pred)
  pr= precision_score(y_test, y_pred)
  f1= f1_score(y_test, y_pred)

  print('정확도:', np.around(acc,4))
  print('재현율', np.around(re,4))
  print('정밀도:', np.around(pr,4))
  print('f1:',np.around(f1,4))

In [ ]:
print_metrics(y_test, y_pred)

정확도: 0.7857
재현율 0.5849
정밀도: 0.7381
f1: 0.6526


### 4. 튜닝

In [ ]:
grid_params = {
    'C': list(range(1,10)),'kernel':['linear', 'poly','rbf'], 'gamma': [0.1,0.5,1,1.5,2.0]
}



In [ ]:
# svm을 사용하여 fit 해보기

clf=SVC()
grid= GridSearchCV(clf,grid_params, cv=5)
grid.fit(x_train_s, y_train)

NameError: ignored